# Étape 1 : Utilisation de Node.js
FROM node:22.13.1

WORKDIR /app/frontend

# Copier uniquement le package.json
COPY frontend/package.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code du frontend
COPY frontend/. ./

# Lancer Vite en mode développement
CMD ["npm", "run", "dev"]