services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chatsync-app
    depends_on:
      - mysqldb
    environment:
      NODE_ENV: development
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: chat_sync
      PORT: 8080
      HOST: "0.0.0.0"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chatsync-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: npm run --prefix frontend preview -- --port 3000

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: chat_sync
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
